"use client";

import { useState } from "react";
import DailyBriefingView from "@/components/DailyBriefing";
import ScoresView from "@/components/ScoresView";
import HowItWorks from "@/components/HowItWorks";
import GroupsView from "@/components/GroupsView";
import BracketView from "@/components/BracketView";
import RankingsTable from "@/components/RankingsTable";
import TeamsView from "@/components/TeamsView";
import ScheduleView from "@/components/ScheduleView";
import InstallBanner from "@/components/InstallBanner";
import { TOURNAMENT } from "@/lib/worldcup-data";

const TABS = [
  { id: "today", label: "Today", emoji: "📅" },
  { id: "scores", label: "Scores", emoji: "⚽" },
  { id: "how", label: "How it works", emoji: "📖" },
  { id: "groups", label: "Groups", emoji: "🗂️" },
  { id: "bracket", label: "Bracket", emoji: "🏆" },
  { id: "rankings", label: "Rankings", emoji: "📊" },
  { id: "teams", label: "Teams", emoji: "🌍" },
  { id: "schedule", label: "Schedule", emoji: "🗓️" },
] as const;

type TabId = (typeof TABS)[number]["id"];

export default function HomePage() {
  const [tab, setTab] = useState<TabId>("today");

  return (
    <main className="max-w-6xl mx-auto px-4 py-8 md:py-10">
      <header className="text-center mb-6">
        <div className="text-4xl mb-1">⚽🏆</div>
        <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight">
          World Cup 2026
        </h1>
        <p className="text-emerald-200/70 text-sm mt-1">
          A beginner&apos;s tracker · {TOURNAMENT.hosts} · {TOURNAMENT.dates}
        </p>
      </header>

      <InstallBanner />

      {/* Tab nav */}
      <nav className="flex flex-wrap justify-center gap-2 mb-8">
        {TABS.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={`text-sm px-4 py-2 rounded-full border transition ${
              tab === t.id
                ? "bg-emerald-500 text-emerald-950 border-emerald-500 font-semibold"
                : "border-white/15 text-emerald-100/80 hover:border-emerald-400/50"
            }`}
          >
            <span className="mr-1">{t.emoji}</span>
            {t.label}
          </button>
        ))}
      </nav>

      <section>
        {tab === "today" && <DailyBriefingView />}
        {tab === "scores" && <ScoresView />}
        {tab === "how" && <HowItWorks />}
        {tab === "groups" && <GroupsView />}
        {tab === "bracket" && <BracketView />}
        {tab === "rankings" && <RankingsTable />}
        {tab === "teams" && <TeamsView />}
        {tab === "schedule" && <ScheduleView />}
      </section>

      <footer className="mt-14 text-center text-xs text-emerald-200/50 space-y-1">
        <p>
          Made for newcomers to soccer. Team data and early results are a snapshot — for live scores
          check an official source.
        </p>
        <p>
          The &quot;Today&quot; update is generated by Claude (add an ANTHROPIC_API_KEY for fresh
          daily write-ups; otherwise a sample update is shown).
        </p>
      </footer>
    </main>
  );
}
